service: expressInAWSDemo #Name of your App

provider:
 name: aws
 runtime: nodejs10.x # Node JS version
 memorySize: 128
 timeout: 15
 region: us-east-1 # AWS region

functions:
  api:
    name: api-insurance
    handler: lambda.handler
    events:
      - http: ANY {proxy+}
      - http: ANY /